[package]
name = "engine_ecs"
version.workspace = true
edition.workspace = true

[dependencies]
engine_core = { path = "../core" }
engine_input = { path = "../input" }
engine_time = { path = "../time" }

bevy_ecs = { workspace = true }
log = { workspace = true }
